"""GFGW-FM: Global Fused Gromov-Wasserstein Flow Matching for one-step generation."""

from .default import (
    GFGWConfig,
    ModelConfig,
    DINOConfig,
    OTConfig,
    LossConfig,
    ScheduleConfig,
    TrainingConfig,
    DataConfig,
    EvalConfig,
    LogConfig,
    get_cifar10_config,
    get_imagenet64_config,
    get_imagenet256_config,
    get_lsun_bedroom_config,
    get_lsun_church_config,
    get_lsun_cat_config,
    CONFIG_REGISTRY,
    get_config,
)

__all__ = [
    'GFGWConfig',
    'ModelConfig',
    'DINOConfig',
    'OTConfig',
    'LossConfig',
    'ScheduleConfig',
    'TrainingConfig',
    'DataConfig',
    'EvalConfig',
    'LogConfig',
    'get_cifar10_config',
    'get_imagenet64_config',
    'get_imagenet256_config',
    'get_lsun_bedroom_config',
    'get_lsun_church_config',
    'get_lsun_cat_config',
    'CONFIG_REGISTRY',
    'get_config',
]
